### ISSUE TITLE
Création de chaine de langue et séléction

### ISSUE THREAD

**Issue by phenix-factory** [bystrano/spip-mode#10]
Si je sélectionne un élément dans le code il faudrai qu'il le récupère automatiquement pour créer la chaine de langue

**Comment by bystrano** [comment]
Yop ! Le commit fc3bb2561beba6ad75206f52bcdaa9bd1f5b3b6a devrait régler ça, et même plus ! On élargi la sélection automatiquement (juste besoin de mettre le curseur dans le string à traduire), et on la remplace par la chaîne de langue qui va bien, avec T('module:chaine') ou <:module:chaine:> !
