### ISSUE TITLE
Problème entre Spacemacs et spip-mode

### ISSUE THREAD

**Issue by phenix-factory** [bystrano/spip-mode#11]
Il faudrai jeter un oeil à ça : https://github.com/syl20bnr/spacemacs/issues/7125#issuecomment-247770221

**Comment by bystrano** [comment]
f25a1591eb2219c5ca30b2dd4ceb3c1def0858a2 devrait corriger ça ! Tu confirmes ?

Au passage ça corrige un autre problème, merci !
