### ISSUE TITLE
Le dossier prive/ est mal géré

### ISSUE THREAD

**Issue by phenix-factory** [bystrano/spip-mode#6]
La surcharge du dossier prive/ est mal gérer. Par exemple les formulaires prive/formulaire/\* qui sont surcharger dans squelettes/ créer un squelettes/prive/formulaires/*.

**Comment by bystrano** [comment]
Mmm, le cas des formulaires est un peu spécial… Mais dans l'idée quand tu surcharges un fichier de l'espace privé, p.ex. dans un plugin, c'est comme ça qu'il faut faire non ? Je pense qu'il faut juste faire une exception pour les formulaires.

**Comment by phenix-factory** [comment]
Je dois t'avoué que depuis que SPIP est dans web-mode je n'utilise que le web-mode et plus le spip-mode.
Faudra que je le retest :).

Je me demande s'il n'y a que les formulaires qui sont à mettre en exception ? Je crois qu'il y a un autre cas, mais je ne revient plus dessus :/

**Comment by bystrano** [comment]
Ça doit être les modèles, non ? Dans les deux cas on ne fait pas un INCLURE, mais on passe par une balise spéciale qui fonctionne selon des règles un peu différentes...

Du coup en traitant différement les formulaires et les modèles on devrait régler le souci (tant que saisies n'est pas dans le core... :-))
