### ISSUE TITLE
Surcharge non fonctionnel

### ISSUE THREAD

**Issue by phenix-factory** [bystrano/spip-mode#8]
Hello,
Donc, je surcharge /squelettes-dist/modeles/lesauteurs.html et il crée ça : 

![selection_001](https://cloud.githubusercontent.com/assets/1810149/18051076/ab4cf236-6df2-11e6-928e-1d8310775287.png)

**Comment by bystrano** [comment]
j'arrive pas à reproduire avec tout à jour… réglé entre temps ?
